# Generated by Django 4.2.9 on 2026-04-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'month', 'year'], name='budgets_bud_user_id_8e3844_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'category'], name='budgets_bud_user_id_72baec_idx'),
        ),
    ]
