# Generated by Django 4.2.9 on 2026-04-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('BOTH', 'Both')], default='EXPENSE', max_length=10),
        ),
    ]
