# Generated by Django 4.2.9 on 2026-04-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='expenses_ex_user_id_713a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category'], name='expenses_ex_user_id_45749f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'is_recurring'], name='expenses_ex_user_id_03ba42_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date', 'amount'], name='expenses_ex_date_bcf230_idx'),
        ),
    ]
