# Generated by Django 4.2.9 on 2026-05-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_expenses_ex_user_id_713a9d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_date_bcf230_idx',
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date', 'amount', 'currency'], name='expenses_ex_date_1d1938_idx'),
        ),
    ]
