# Generated by Django 4.2.9 on 2026-04-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['user'], name='savings_sav_user_id_30e1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['user', 'deadline'], name='savings_sav_user_id_f55a00_idx'),
        ),
    ]
