# Generated by Django 4.2.9 on 2026-05-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_savingsgoal_savings_sav_user_id_30e1f9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
