# Generated by Django 4.2.9 on 2026-04-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_telegram_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_chat_id'], name='users_user_telegra_1e47e4_idx'),
        ),
    ]
