# Generated by Django 4.2.9 on 2026-05-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
