# Generated by Django 4.2.9 on 2026-04-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income_category_income_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'date'], name='income_inco_user_id_f74de7_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'category'], name='income_inco_user_id_04ffe9_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'is_recurring'], name='income_inco_user_id_327894_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['date', 'amount'], name='income_inco_date_8ef77e_idx'),
        ),
    ]
