# Generated by Django 4.2.9 on 2026-05-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_income_income_inco_user_id_f74de7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='income',
            name='income_inco_date_8ef77e_idx',
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['date', 'amount', 'currency'], name='income_inco_date_f04789_idx'),
        ),
    ]
